name: ci test
on: [push]

jobs:
  py37:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Test - print python version
      run: python --version
    - name: Test - ls
      run: |
        echo ~
        ls -la
        python -c 'print(7*8)'