name: CI
on: [push]

jobs:

  build:
    name: test build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: echo aabb > z.txt
    - run: cat z.txt
    - run: readlink -f ./z.txt
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./z.txt
        retention-days: 1

  py39:
    runs-on: ubuntu-20.04
    needs: build
    name: setup for python ${{ matrix.py }}
    strategy:
      matrix:
        py: [3.8, 3.9]
      
        include:
          - py: 3.8
            deps: numpy==1.19.4 scipy pytest
            scipy: true
          - py: 3.9
            deps: scipy numpy pytest
            scipy: false
    
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Load artifact
      uses: actions/download-artifact@v2
      with:
        name: build
        path: ./zz.txt
    - run: ls zz.txt
    
    - name: Test - print python version
      run: python --version
    - name: Install dependencies
      run: |
        pip install ${{ matrix.deps }}
        python -c 'import numpy; print(f"{numpy.__version__=}")'
        python -c 'import scipy; print(f"{scipy.__version__=}")'
    - if: ${{ matrix.scipy }}
      run: |
        echo scipy is ${{ matrix.scipy }}
      