name: CI
on: [push]

jobs:
  py39:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        py: [3.8, 3.9]
      
        include:
          - py: 3.8
            npver: 1.19.4
          - py: 3.9
            npver: 1.19.4
    
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}
    - name: Test - print python version
      run: python --version
    - name: Install dependencies
      run: |
        pip install numpy==${{ matrix.npver }} scipy pytest
        python -c 'import numpy; print(f"{numpy.__version__=}")'
        python -c 'import scipy; print(f"{scipy.__version__=}")'
        python -c 'import pytest; print(f"{pytest.__version__=}")'
      