name: ci test
on: [push]

jobs:
  py37:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Test - print python version
      run: python --version
    - name: Test - ls
      run: |
        echo ~
        ls -la
        python -c 'print(7*8)'
        cat .github/workflows/ci.yml
    - name: Install dependencies
      run: exit 1
      