name: CI
on: [push]

jobs:

  build:
    name: test build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: echo aabb > z.txt
    - run: cat z.txt
    - run: readlink -f ./z.txt
    - uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./z.txt
        retention-days: 1

  test:
    runs-on: ubuntu-20.04
    needs: build
    name: >
      setup for python ${{ matrix.py }} with the following 
      dependencies ${{ matrix.deps }}
    strategy:
      matrix:
        # py: [3.9]
      
        include:
          - py: 3.9
            deps: scipy numpy pytest
            scipy: false
            text-flag: 'abc'
    
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - name: Load artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./dist
      - run: ls dist
      
      - run: echo "${{ matrix.text-flag }}"
      
      - run: |
          cd dist
          readlink -f .
            
      - name: Test - print python version
        run: python --version
      
      - name: Install dependencies
        run: |
          pip install ${{ matrix.deps }}
          # python -c 'import numpy; print(f"{numpy.__version__=}")'
          # python -c 'import scipy; print(f"{scipy.__version__=}")'
      - if: ${{ (!matrix.scipy) || true }}
        run: |
          echo scipy is ${{ matrix.scipy }}
      